import { Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navber/NavBar";
import Footer from "../components/footer/Footer";

import Banner from "../components/banner/Banner";
import TopCard from "../components/top-5-card/TopCard";

const OutfitFont = Outfit({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className} h-full antialiased`}
    >
      <body>
        <NavBar></NavBar>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
